// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxoq8qtiUfw7RYhPzP3HltR0CZ6fNQX68',
    appId: '1:947492197474:web:3140468d6719a19c6bed3b',
    messagingSenderId: '947492197474',
    projectId: 'hasan-alturk',
    authDomain: 'hasan-alturk.firebaseapp.com',
    storageBucket: 'hasan-alturk.appspot.com',
    measurementId: 'G-L7D8E1HEFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDddPzoAwVrFF0HbDCVBtSIn4lShQ9Gg28',
    appId: '1:947492197474:android:8f728c765c06b0ed6bed3b',
    messagingSenderId: '947492197474',
    projectId: 'hasan-alturk',
    storageBucket: 'hasan-alturk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM5Upl9kUwLsB73duJ7IJznyupEIiPJN8',
    appId: '1:947492197474:ios:0ed77e86f6c9f9916bed3b',
    messagingSenderId: '947492197474',
    projectId: 'hasan-alturk',
    storageBucket: 'hasan-alturk.appspot.com',
    iosBundleId: 'com.example.blackMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM5Upl9kUwLsB73duJ7IJznyupEIiPJN8',
    appId: '1:947492197474:ios:03da11cac28c45686bed3b',
    messagingSenderId: '947492197474',
    projectId: 'hasan-alturk',
    storageBucket: 'hasan-alturk.appspot.com',
    iosBundleId: 'com.example.blackMarket.RunnerTests',
  );
}
