// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSZnb_B5RKb9uU9LQgyzuRD5ST8VF3P4',
    appId: '1:829943681282:web:e829a3f3456f37d167f21b',
    messagingSenderId: '829943681282',
    projectId: 'blackmarketalturk',
    authDomain: 'blackmarketalturk.firebaseapp.com',
    storageBucket: 'blackmarketalturk.appspot.com',
    measurementId: 'G-WVLK2DNSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcuwpHz5fgtsepj8Zu8aph1gTn6NmGcg',
    appId: '1:829943681282:android:4a72be359c9698ed67f21b',
    messagingSenderId: '829943681282',
    projectId: 'blackmarketalturk',
    storageBucket: 'blackmarketalturk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OQDBYpp3XkpuZNw0hNcEic1I_bCcsjY',
    appId: '1:829943681282:ios:1053c0bcd3a1e88a67f21b',
    messagingSenderId: '829943681282',
    projectId: 'blackmarketalturk',
    storageBucket: 'blackmarketalturk.appspot.com',
    iosBundleId: 'com.example.blackMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8OQDBYpp3XkpuZNw0hNcEic1I_bCcsjY',
    appId: '1:829943681282:ios:c21d92d830a0958b67f21b',
    messagingSenderId: '829943681282',
    projectId: 'blackmarketalturk',
    storageBucket: 'blackmarketalturk.appspot.com',
    iosBundleId: 'com.example.blackMarket.RunnerTests',
  );
}
